env:
  - GO111MODULE=on
before:
  hooks:
    - go version
    - go mod tidy
builds:
  - id: nowin
    env:
      - CGO_ENABLED=1
      - GO111MODULE=on
    goos:
      - linux
      - darwin
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: 386
    flags:
      - -trimpath
    ldflags:
      - -s -w

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - fix typo
      - Merge pull request
      - Merge branch
      - Merge remote-tracking
      - go mod tidy

archives:
  - id: nowin
    builds:
      - nowin
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

nfpms:
  - license: GPL 3.0
    homepage: https://github.com/FloatTech/ZeroBot-Plugin-Dynamic
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
    maintainer: Fumiama